### ISSUE TITLE
SDK level requirement 16 because of the included example project.

### ISSUE THREAD

**Issue by gnumilanix** [facebook/shimmer-android#10]
The library itself requires sdk level 11 as minimum but, the included sample project sets the minimum sdk to 16. This causes including the library to set the minimum level to 16, when it can be done in api level 11.

**Comment by Aracem** [comment]
I have the same error when try to use this library. Finally We decided to use the .jar but, of course, much better if we can use gradle.

**Comment by MarsVard** [comment]
bump
