### ISSUE TITLE
After shimmer is stopped I have my view still have shimmer_base_alpha setup

### ISSUE THREAD

**Issue by s7aycool** [facebook/shimmer-android#101]
When I set containter.setShimmering(false) my button is getting stuck with inactive shimmer on it, and it also becomes enabled = false.
How to bring back origin color for my view and stop disabling it on stopShimmering?

**Comment by JustusKlawischS2** [comment]
you can use `app:shimmer_base_alpha="1.0"` to make the shimmer overlay transparent. The default value of baseAlpha is 0.3, have a look at `com.facebook.shimmer.SchimmerDrawable` for all default values.

**Comment by xiphirx** [comment]
start/stop apis will start/stop the animation only.
show/hide apis will show/hide the shimmer + start/stop the animation.
