### ISSUE TITLE
While using in fragment background becomes transparent due to which views in activity are visible

### ISSUE THREAD

**Issue by mhrjnamar** [facebook/shimmer-android#104]

**Comment by krishnendu25** [comment]
<RelativeLayout
        android:id="@+id/shimmerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/background_base">
        <com.facebook.shimmer.ShimmerFrameLayout
            android:id="@+id/shimmer_view_container"
            android:layout_width="match_parent"
            android:duration="300"
            android:background="@color/transparent"
            android:layout_gravity="center_horizontal"
            android:layout_height="match_parent">
            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@color/black">
                <ImageView
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:background="@drawable/shimmer_rides"/>
            </RelativeLayout>

        </com.facebook.shimmer.ShimmerFrameLayout>
    </RelativeLayout>

**Comment by krishnendu25** [comment]
public void show_ProgressDialog() {
        shimmer_view_container.startShimmer();
        shimmerView.setVisibility(View.VISIBLE);
    }

    public void hide_ProgressDialog() {
        shimmer_view_container.stopShimmer();
        shimmerView.setVisibility(View.GONE);
    }

**Comment by xiphirx** [comment]
I do not know what this issue is describing, please provide more details.
