### ISSUE TITLE
This library is increasing the size of the app

### ISSUE THREAD

**Issue by shahzad1** [facebook/shimmer-android#110]
Before implementing the library, the app size was 6 MB, but after adding this library, the app size is now 8.95 MB.
Any solution to avoid app size?

**Comment by KaustubhPatange** [comment]
This is impossible as 
 this library only contains 3 classes which shouldn't even go over 100 kb in size.

**Comment by xiphirx** [comment]
This library only ships a few classes and no resources, unless you can show that the dependency aar is almost 3MiB I can't help you.
