### ISSUE TITLE
Attribute "intensity" has already been defined

### ISSUE THREAD

**Issue by PatrickDattilio** [facebook/shimmer-android#12]
It appears both shimmer-android and Fabric libraries and define the attribute "intensity". Could you prefix your libraries attributes as per https://code.google.com/p/android/issues/detail?id=22576?

...app\build\intermediates\exploded-aar\com.twitter.sdk.android\twitter-core\1.4.0\res\values\values.xml
Error:(2) Attribute "intensity" has already been defined

**Comment by xiphirx** [comment]
a360eb1efec5b32b7fa6ed8eeca46703df415bc3
