### ISSUE TITLE
ListView animation freezes

### ISSUE THREAD

**Issue by mastrgamr** [facebook/shimmer-android#13]
Every time I use the widget in a ListView with more than 3 or 4 items using the viewholder pattern, the list items after that 3rd or 4th item does not animate.

I've tried to startAnimation programatically and also tried setting the app:auto_start attribute to true in the layout's attributes.

**Comment by esiek** [comment]
In RecyclerView animation freezes too :(

**Comment by pakidanish** [comment]
i found solution. 

 final View finalConvertView = convertView;

            new Thread(new Runnable() {
                public void run() {
                    activity.runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            ShimmerFrameLayout shimmer_view_container = (ShimmerFrameLayout) finalConvertView.findViewById(R.id.shimmer_view_container);

                            shimmer_view_container.stopShimmerAnimation();

                            shimmer_view_container.startShimmerAnimation();

                        }
                    });
                }
            }).start();

**Comment by dlleixap** [comment]
Based on @pakidanish solution I found a simpler way.

```
ShimmerFrameLayout shimmer = (ShimmerFrameLayout) finalConvertView.findViewById(R.id.shimmer);
binding.shimmer.post(new Runnable() {
    @Override
    public void run() {
        binding.shimmer.startShimmerAnimation();
    }
});
```
Or even nicer when using lamdas:
`shimmer.post(binding.shimmer::startShimmerAnimation);`
