### ISSUE TITLE
Animation status when set visibility to GONE

### ISSUE THREAD

**Issue by MoustafaElsaghier** [facebook/shimmer-android#141]
I'd like to know what will happen on the memory side in the case of a developer called `shimmerLayout.isVisible = false` without calling `stopShimmer()`

will **ShimmerLayout** handle stop on its own **OR** animation will keep running and consuming memory and must call `stopShimmer()`?

I've checked the code but, I couldn't find anywhere `mValueAnimator.cancel()` out of bounds `stopShimmer()` and `setShimmer()`

so, please can someone assist with that question, please?

**Comment by emresarincioglu** [comment]
It calls `stopShimmer()` when visibility set to gone or invisible. See [onVisibilityChanged](https://github.com/facebook/shimmer-android/blob/main/shimmer/src/main/java/com/facebook/shimmer/ShimmerFrameLayout.java#L153)

**Comment by MoustafaElsaghier** [comment]
thank you, noted
