### ISSUE TITLE
how can i change the colour of the shimmer light

### ISSUE THREAD

**Issue by kency2015** [facebook/shimmer-android#17]
i want to create a view which has a bright-white light over the whole view , but when i used this library , the color of the shimmer light always depends on the color of the view's background ,for example , when  a view'background is yellow ,the shimmer light is yellow too , but what i want is that the colour of the shimmer light is brght white.  how can i make this?

**Comment by ninovanhooff** [comment]
I would also like to set the color/alpha of the shimmer. To arrive at less than pure white, I currently have reduce the alpha of the whole view, which is not efficient

**Comment by zhangyun136731** [comment]
I also have this problem

**Comment by stevenchans** [comment]
upstairs  +1

**Comment by xiphirx** [comment]
544c5687cc0f1b2e976cd43e806a5f82e81d6462

**Comment by mecoFarid** [comment]
This issue should be reopened, I guess, or I'm missing out something. Trying to have a shimmer highlight with a different color rather than highlight with alpha.

> Setting both `app:shimmer_colored="true"` and `app:shimmer_highlight_color="@color/colorAccent"` removes shimmer effect from children (shimmer applied to parent only).

```
<?xml version="1.0" encoding="utf-8"?>
<com.facebook.shimmer.ShimmerFrameLayout
    android:id="@+id/shimmer_loader_view"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:shimmer_colored="true"
    app:shimmer_highlight_color="@color/colorAccent"
    app:shimmer_duration="1500">

                <Parent>
                     <Child>
                     <Child>
                     <Child>
                </Parent>

</com.facebook.shimmer.ShimmerFrameLayout>
```

**Comment by nishanthvasu** [comment]
Hi Guys,

Was this issue resolved ? If so please say me how it got fixed ?

**Comment by yanayhollander** [comment]
using `app:shimmer_highlight_alpha="0"` resolved the issue for me.

    <com.facebook.shimmer.ShimmerFrameLayout
        android:id="@+id/shimmer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:shimmer_highlight_alpha="0">

                <Parent>
                     <Child>
                     <Child>
                     <Child>
                </Parent>

    </com.facebook.shimmer.ShimmerFrameLayout>

**Comment by dinopriyano** [comment]
> 
> 
> using `app:shimmer_highlight_alpha="0"` resolved the issue for me.
> 
> ```
> <com.facebook.shimmer.ShimmerFrameLayout
>     android:id="@+id/shimmer"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     app:shimmer_highlight_alpha="0">
> 
>             <Parent>
>                  <Child>
>                  <Child>
>                  <Child>
>             </Parent>
> 
> </com.facebook.shimmer.ShimmerFrameLayout>
> ```

nice bro

**Comment by oth-libs** [comment]
why do views inside the layout have alpha already? how can I have the views with the correct color?

**Comment by kalyanrevuru** [comment]
app:shimmer_highlight_alpha="0" not found error

**Comment by wasimasghar** [comment]
@mecoFarid solution works for me...
 Issue fixed by using these two attributes.
  app:shimmer_colored="true"
  app:shimmer_highlight_color="@color/colorAccent"
