### ISSUE TITLE
Error inflating class com.facebook.shimmer.ShimmerFrameLayout

### ISSUE THREAD

**Issue by bb1690** [facebook/shimmer-android#21]
used jar instead of adding it as compile statement in dependencies. worked fine in demo. but not working in project. Bcause adding dependency was giving me Error:(593) Attribute “shape” already defined with incompatible format this error.

java.lang.RuntimeException: Unable to start activity ComponentInfo
android.view.InflateException: Binary XML file line #41: Binary XML file line #41: Error inflating class com.facebook.shimmer.ShimmerFrameLayout.

**Comment by coplas** [comment]
I had the same problem, my problem was I started to use 
compile 'com.android.support.constraint:constraint-layout:1.0.2'
and worked before, when using 
compile 'com.android.support.constraint:constraint-layout:1.0.0-beta4'

**Comment by coplas** [comment]
Try this dependency (forked and updated versions to current):

compile 'com.github.coplas:shimmer-android:0.1.1'

Also jitpack repo is required
repositories {
    maven { url "https://jitpack.io" }
}

I Also created pull request

**Comment by aradhell** [comment]
I am facing the same problem. And compile 'com.github.coplas:shimmer-android:0.1.1 couldn't fix it.

Error:(806) Attribute "shape" already defined with incompatible format.

    
`<declare-styleable name="ShimmerFrameLayout"><attr format="boolean" name="auto_start"/><attr format="float" name="base_alpha"/><attr format="integer" name="duration"/><attr format="integer" name="repeat_count"/><attr format="integer" name="repeat_delay"/><attr format="enum" name="repeat_mode"><enum name="restart" value="1"/><enum name="reverse" value="2"/></attr><attr format="enum" name="angle"><enum name="cw_0" value="0"/><enum name="cw_90" value="90"/><enum name="cw_180" value="180"/><enum name="cw_270" value="270"/></attr><attr format="float" name="dropoff"/><attr format="dimension" name="fixed_width"/><attr format="dimension" name="fixed_height"/><attr format="float" name="intensity"/><attr format="float" name="relative_width"/><attr format="float" name="relative_height"/><attr format="enum" name="shape"><enum name="linear" value="0"/><enum name="radial" value="1"/></attr><attr format="float" name="tilt"/></declare-styleable>`

   ` <declare-styleable name="PagerIndicator"><attr format="enum" name="visibility"><enum name="visible" value="0"/><enum name="invisible" value="1"/></attr><attr format="enum" name="shape"><enum name="oval" value="0"/><enum name="rect" value="1"/></attr><attr format="color" name="selected_color"/><attr format="color" name="unselected_color"/><attr format="reference" name="selected_drawable"/><attr format="reference" name="unselected_drawable"/><attr format="dimension" name="selected_width"/><attr format="dimension" name="selected_height"/><attr format="dimension" name="unselected_width"/><attr format="dimension" name="unselected_height"/><attr format="dimension" name="padding_left"/><attr format="dimension" name="padding_right"/><attr format="dimension" name="padding_top"/><attr format="dimension" name="padding_bottom"/><attr format="dimension" name="selected_padding_left"/><attr format="dimension" name="selected_padding_right"/><attr format="dimension" name="selected_padding_top"/><attr format="dimension" name="selected_padding_bottom"/><attr format="dimension" name="unselected_padding_left"/><attr format="dimension" name="unselected_padding_right"/><attr format="dimension" name="unselected_padding_top"/><attr format="dimension" name="unselected_padding_bottom"/></declare-styleable>`

**Comment by korva** [comment]
I ran to this issue after updating to Android Studio 3.0 and updating a bunch of google libraries while at it. The forked version by @coplas works for me.

**Comment by DarushDev** [comment]
This fixed my problem:
````java
// Gradle dependency on Shimmer for Android
dependencies {
       compile 'com.facebook.shimmer:shimmer:0.1.0@aar'
 }

**Comment by ashraf-patel** [comment]
I am still facing the issue, I've added jar in libs, because I am facing the same problem. And compile 'com.github.coplas:shimmer-android:0.1.1 couldn't fix it.

Error:(806) Attribute "shape" already defined with the incompatible format.

**Comment by amitpawar399** [comment]
getting same issue 
Error:(846) Attribute "shape" already defined with incompatible format.
Please help

**Comment by xiphirx** [comment]
a360eb1efec5b32b7fa6ed8eeca46703df415bc3

**Comment by mancyzbooni** [comment]
Hi , i tried with the gradle dependencies gave me error the shape is already present error . Now i switched to jar file , i was able to run but Error inflating class com.facebook.shimmer.ShimmerFrameLayout i get this error and app crashes . Plase help when i tries coplas version same old error repeats Error:(203, 5) Attribute "shape" already defined with incompatible format. 
. Please reply

**Comment by NiroopNife** [comment]
Try this
implementation 'com.facebook.shimmer:shimmer:0.5.0'
