### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by maher640** [facebook/shimmer-android#25]
is there a way to make the shimmer effect from Right To Left?

**Comment by maher640** [comment]
found it. you have to set the angle as 
`.setAngle(ShimmerFrameLayout.MaskAngle.CW_180); `
for animation from Right To Left.

**Comment by anoopmaddasseri** [comment]
XML Attr:  ` app:shimmer_direction=""`

**Programmatically**

```
// Set direction of the shimmer's sweep.
val builder = Shimmer.AlphaHighlightBuilder()
builder.setDirection(getShimmerDirection())
binding.sflShimmer.setShimmer(builder.build())

private fun getShimmerDirection() =
        if (DeviceUtils.isLTR()) Shimmer.Direction.LEFT_TO_RIGHT else Shimmer.Direction.RIGHT_TO_LEFT
```

**Comment by abdulsalam-alhammadi** [comment]
You can use this attribute on xml
  app:shimmer_direction="right_to_left"
