### ISSUE TITLE
Not working in MIUI

### ISSUE THREAD

**Issue by Ishaan-Kumar** [facebook/shimmer-android#28]
I am using this library: https://github.com/sharish/ShimmerRecyclerView which depends on facebook shimmer library.
The adapter part is working fine but shimmer (by facebook is not woking at all).
Please fix.
BTW, perfectly working on stock android (My Moto E 2nd Gen Android API 21)

Problem on: MIUI Redmi 3S Prime Android API 23 MIUI Version Global 8.1 (8.1.1.0 MALMIDI)

**Comment by xiphirx** [comment]
Closing due to age of issue.
