### ISSUE TITLE
Error:(471) Attribute "shape" already defined with incompatible format.

### ISSUE THREAD

**Issue by HasanShaikh** [facebook/shimmer-android#29]
I am trying to include the gradle dependency into my app. After adding the dependency and rebuilding the app it is giving the above mentioned issue. Please let me know how to fix this issue.

**Comment by amitpawar399** [comment]
i am getting same issues, 
Error:(746) Attribute "shape" already defined with incompatible format.

Please help

**Comment by xiphirx** [comment]
a360eb1efec5b32b7fa6ed8eeca46703df415bc3

**Comment by DibSarkar** [comment]
I'm also getting the same error
