### ISSUE TITLE
auto_start stopped working with AndroidStudio 3.0

### ISSUE THREAD

**Issue by mitsest** [facebook/shimmer-android#36]
Also, when calling startShimmerAnimation() from inside the code, the animation makes the shimmer layout transparent

**Comment by tijee** [comment]
Same problem, did you find a fix or a workaround?

**Comment by mitsest** [comment]
Unfortunately no.
I think this release of android studio broke this plugin (see also the next issue)

The visual workaround was to make the shimmer layout a lighter gray :/

I guess, we have to wait till the devs respond, or dive in and figure it out ourselves

**Comment by karanthakral** [comment]
is this library still maintained? Getting a similar issue and also a lot of memory crashes?..Any alternatives to this

**Comment by veghtomi** [comment]
@karanthakral Try [ShimmerLayout](https://github.com/team-supercharge/ShimmerLayout)

**Comment by xiphirx** [comment]
544c5687cc0f1b2e976cd43e806a5f82e81d6462
