### ISSUE TITLE
How to exclude some views

### ISSUE THREAD

**Issue by AlexisQapa** [facebook/shimmer-android#39]
Hi, 

Looking at the documentation I didn't found a way to exclude some views from the animation. Is there a way to achieve this without having multiple shimmers ?

Here is what I'd like to have with Separator and TextView not animated : 

```
<ShimmerL>
<ConstraintL>
<View>
<View>
<Separator>
<TextView>
<View>
<View>
</ConstL>
</Shimmer>
```

The thing is with a complex layout it's nice to flatten it with constraint layout. Having (multiple) ShimmerLayout inside my constraint layout remove the ability to setup constraint within childs views.

**Comment by xiphirx** [comment]
Unfortunately not. We can't really know what to exclude when drawing the shimmer as its all done via shaders + porter duff xfer modes.
