### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by tianzhijiexian** [facebook/shimmer-android#4]
03-12 10:05:31.064: E/AndroidRuntime(15217): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.facebook.shimmer.example/com.facebook.shimmer.example.MainActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class com.facebook.shimmer.ShimmerFrameLayout
03-12 10:05:31.064: E/AndroidRuntime(15217): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2187)

**Comment by jasleensingh** [comment]
Can you provide some more information, like some example code and your build files (are you using gradle or importing the .aar file into your project)? It's difficult to diagnose the problem with the trace you provided.

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by tianzhijiexian** [comment]
thx.

**Comment by dkpalmer** [comment]
Just to add some more info for anyone that comes across this, I also ran into the inflation exception. I was missing the @aar on the reference in Gradle. Adding it cleared the exception.
