### ISSUE TITLE
 Error inflating class com.facebook.shimmer.ShimmerFrameLayout

### ISSUE THREAD

**Issue by mancyzbooni** [facebook/shimmer-android#48]
Binary XML file line #201: Binary XML file line #201: Error inflating class com.facebook.shimmer.ShimmerFrameLayout
                                                                    Caused by: android.view.InflateException: Binary XML file line #201: Error inflating class com.facebook.shimmer.ShimmerFrameLayout

I have tried the gradle way it gives me "shape is already defined error"  . So i tried with jar file and i was able to integrate but when i run the project i get the above error and app crashes . 

i did follow the commit of removing the shimmer:animation and trying to take off the constraint layout as well . Stil its same . please help . The error is not resolved for me . i did see the issue #20 closed . But whats the solution to this ?

**Comment by xiphirx** [comment]
This error is resolved in the next version. Please either use a snapshot or wait until 0.2.0 is released. I will look into releasing it soon.
