### ISSUE TITLE
Shimmering does not stop after calling .stopShimmer()

### ISSUE THREAD

**Issue by ArcherEmiya05** [facebook/shimmer-android#51]
Hello I would like to ask why is shimmering still exist even after calling .stopShimmer() method in RecyclerView. Here's an example I am using 0.2.0 v.

            //Set the user's profile picture
            this.shimmerSUDP.startShimmer();
            GlideApp.with(context)
                    .load(thumbnail)
                    .placeholder(R.color.icon_not_selected)
                    .diskCacheStrategy(DiskCacheStrategy.AUTOMATIC)
                    .listener(new RequestListener<Drawable>() {
                        @Override
                        public boolean onLoadFailed(@Nullable GlideException e, Object model, 
                                Target<Drawable> target, boolean isFirstResource) {
                            return false;
                        }

                        @Override
                        public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> 
                          target, DataSource dataSource, boolean isFirstResource) {
                            shimmerSUDP.stopShimmer();
                            return false;
                        }
                    })
                    .into(mSuDP);

**Comment by xiphirx** [comment]
`stopShimmer` seems to be working as expected when trying it out in the sample app. Are you sure the view holder wasn't re-instantiated and dont have `autoStart` specified?

**Comment by ArcherEmiya05** [comment]
Wow! So autostart is the culprit here. I also notice that thanks anyway.

On 23 May 2018 1:00 a.m., "Hilal Alsibai" <notifications@github.com> wrote:

stopShimmer seems to be working as expected when trying it out in the
sample app. Are you sure the view holder wasn't re-instantiated and dont
have autoStart specified?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/shimmer-android/issues/51#issuecomment-391065582>,
or mute the thread
