### ISSUE TITLE
The shimmer is drawn at an incorrect position

### ISSUE THREAD

**Issue by yarolegovich** [facebook/shimmer-android#59]
To make this noticeable:
1. Don't set Xfermode on mShimmerPaint to see where mDrawRect is drawn.
2. Decrease ShimmerLayout height.
3. Increase tilt angle to 40 or more.

<img src="https://user-images.githubusercontent.com/9644546/42237551-cbbb23e0-7f06-11e8-989b-4c600ff53c5b.png" width="240"/>

**Comment by xiphirx** [comment]
Thanks!
