### ISSUE TITLE
Latest gradle version

### ISSUE THREAD

**Issue by alvinwoon** [facebook/shimmer-android#6]
Looks like the latest commit reduce the min-sdk requirement. Awesome. When will it get pushed to maven?

**Comment by jasleensingh** [comment]
Pushed to Maven.

**Comment by eeVoskos** [comment]
I'm still getting this error when trying to set minSdkVersion to anything lower than 16:
```Manifest merger failed: uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library {path}/build/intermediates/exploded-aar/com.facebook.shimmer/shimmer/0.1.0/AndroidManifest.xml```

**Comment by jasleensingh** [comment]
Can you try switching to mavenCentral as your repository, instead of jcenter? Looks like jcenter hasn't picked up the latest update; I'll investigate that, but in the meantime, this is a workaround.

**Comment by eeVoskos** [comment]
Thanks, this worked!
