### ISSUE TITLE
ShimmerFrameLayout With Scrollview

### ISSUE THREAD

**Issue by deshario** [facebook/shimmer-android#62]
Hor to use ShimmerFrameLayout with scrollview properly ?

> 
        <com.facebook.shimmer.ShimmerFrameLayout
            android:id="@+id/shimmer_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center"
            android:orientation="vertical"
            shimmer:duration="1500">

            <ScrollView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:fillViewport="true">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="vertical">

                    <include layout="@layout/pholder_campaign" />
                    <include layout="@layout/pholder_campaign" />
                    <include layout="@layout/pholder_campaign" />

                </LinearLayout>

            </ScrollView>

        </com.facebook.shimmer.ShimmerFrameLayout>

![code](https://user-images.githubusercontent.com/11426727/43355281-07adb49a-9284-11e8-9f91-f7c1b502cdab.PNG)

But My View looks like this when i scroll : 
![shimmer](https://user-images.githubusercontent.com/11426727/43355272-e05d3186-9283-11e8-8a39-2e7799106398.png)

**Comment by xiphirx** [comment]
You want to use the latest version of the library and you also want to wrap the individual items of your scroll view in the shimmer layout instead of the entire scroll view.
