### ISSUE TITLE
Clear Shimmer

### ISSUE THREAD

**Issue by zsweigart** [facebook/shimmer-android#64]
I have an image view inside a shimmer frame layout, when load an image into the image view I want to clear the shimmer entirely but there is no way to do this.  If I stop the shimmer there is still an overlay over my image view.

**Comment by xiphirx** [comment]
Do you need to have the image inside of the `ShimmerFrameLayout` ? Could you instead just hide the `ShimmerFrameLayout` when you're done loading your image?

**Comment by zsweigart** [comment]
Shouldn't the `ShimmerFrameLayout` contain the views? Or are you thinking of using `RelativeLayout` or `FrameLayout` parent view group that holds the shimmer and the image view and overlays them?

I was also able to achieve clearing by doing this:

```
shimmerFrameLayout.setShimmer(
  new Shimmer.AlphaHighlightBuilder()
    .setBaseAlpha(1)
    .setIntensity(0)
    .build());
shimmerFrameLayout.stopShimmer();
shimmerFrameLayout.clearAnimation();
```

But it's pretty ugly

**Comment by xiphirx** [comment]
Typically you have a "dummy" view inside of `ShimmerFrameLayout` that takes the form of the content you expect to be shown. When your content is ready you remove the `ShimmerFrameLayout` + the "dummy" view and show your loaded content.

**Comment by zsweigart** [comment]
Interesting, I can give that a shot.  I think this would be a nice enhancement to the API though.  I'm using Picasso to load an image into my image view so it shimmers while the call is being made over the placeholder image.  Then when the callback is either successful or a failure I clear the shimmer and show the image or the error image.

**Comment by xiphirx** [comment]
The appropriate use there would be to use a `ShimmerDrawable` directly as the placeholder for Picasso while the image loads.

**Comment by DamonBaker** [comment]
This used to be the case in 0.1.0 where calling stopShimmerAnimation() would remove the overlay completely. This was useful when there is content already on the screen which is being "reloaded", or the user performs an action that requires additional loading. In cases like this I don't want to replace preexisting content with a dummy view.

**Comment by xiphirx** [comment]
It seems like a good compromise is letting users call `setShimmer(null)` to remove the shimmer. I can make that change.

**Comment by xiphirx** [comment]
e7a2129f79a6d2c76fceddaf1a8c401e30b4f5b8

**Comment by JayyyR** [comment]
@xiphirx any word on release with this change?

**Comment by xiphirx** [comment]
0.4.0 was just pushed to sonatype.

**Comment by mochadwi** [comment]
> Shouldn't the `ShimmerFrameLayout` contain the views? Or are you thinking of using `RelativeLayout` or `FrameLayout` parent view group that holds the shimmer and the image view and overlays them?
> 
> I was also able to achieve clearing by doing this:
> 
> ```
> shimmerFrameLayout.setShimmer(
>   new Shimmer.AlphaHighlightBuilder()
>     .setBaseAlpha(1)
>     .setIntensity(0)
>     .build());
> shimmerFrameLayout.stopShimmer();
> shimmerFrameLayout.clearAnimation();
> ```
> But it's pretty ugly

Nice workaround, also using setShimmer(null) much cleaner~

**Comment by rfogar2** [comment]
Old issue, but what if you want to remove the shimmer and then add it again, in case of a refresh action? Does `setShimmer(null)` means you will have to rebuild the `Shimmer` instance from scratch?

**Comment by xiphirx** [comment]
You can use the new show/hide methods https://github.com/facebook/shimmer-android/commit/97ca4d1d7cd1ec4e3435ee46a1748da00aa0511e

**Comment by rfogar2** [comment]
@xiphirx Can you cut a new release?

**Comment by xiphirx** [comment]
https://github.com/facebook/shimmer-android/releases/tag/0.5.0

Give it a few minutes to propagate to maven central

**Comment by Sudheer888** [comment]
When I am using shimmer.stopShimmer();  my app is force stoped.
shimmer is working in loop on my project.

**Comment by Shamivul** [comment]
what happens to shimmer when onDestroy() is called after starting the animation? deos it destroy itself or does it need to be handled manually

**Comment by warrior1112** [comment]
> You can use the new show/hide methods [97ca4d1](https://github.com/facebook/shimmer-android/commit/97ca4d1d7cd1ec4e3435ee46a1748da00aa0511e)

thank you so much ! it helped.

**Comment by Piyush0912** [comment]
> Shouldn't the `ShimmerFrameLayout` contain the views? Or are you thinking of using `RelativeLayout` or `FrameLayout` parent view group that holds the shimmer and the image view and overlays them?
> 
> I was also able to achieve clearing by doing this:
> 
> ```
> shimmerFrameLayout.setShimmer(
>   new Shimmer.AlphaHighlightBuilder()
>     .setBaseAlpha(1)
>     .setIntensity(0)
>     .build());
> shimmerFrameLayout.stopShimmer();
> shimmerFrameLayout.clearAnimation();
> ```
> 
> But it's pretty ugly

where we use this code and what we write inside .placeholder in glide library
