### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by Mordag** [facebook/shimmer-android#65]
With the release of Android Studio 3.2.0, is there any plan to update this library to support AndroidX soon?

**Comment by xiphirx** [comment]
We only use the support-annotations artifact from the support library, so its not entirely pressing to update to AndroidX. We will get around to it when it is production ready, likely, though.

**Comment by Mordag** [comment]
@xiphirx Thanks for your reply. FYI, the AndroidX lib got stable last week.
