### ISSUE TITLE
ShimmerFrameLayout inside ShimmerFrameLayout issue

### ISSUE THREAD

**Issue by ArthurMytsko** [facebook/shimmer-android#66]
In case you have ShimmerFrameLayout (outer) inside ShimmerFrameLayout (inner), and you start shimmer for inner view - it also starts shimmer for outer view (at least animate it). Could you please check this?

**Comment by ArthurMytsko** [comment]
Yes, I'm sure. I had to do setShimmer() with no visual effects for outer instance in order to overcome this.
If you are not able to reproduce it - I can send you example

**Comment by xiphirx** [comment]
I'll have to check it out, I'll let you know when I do.

**Comment by xiphirx** [comment]
I just tried this out and I wasn't able to see that starting the inner shimmer caused the outer shimmer to also start. Check that you dont have auto start specified (its on by default) on the outer shimmer.

**Comment by ArthurMytsko** [comment]
Oh.. I've missed the point with auto-start option. Sorry for bothering.
