### ISSUE TITLE
Applying ShimmerFrameLayout to an elevated View in Lollipop "multiplies" the shadow 

### ISSUE THREAD

**Issue by f-barth** [facebook/shimmer-android#7]
It seems that applying the Shimmer-magic to a view does draw lollipop elevation-shadow multiple times. 
In the picture below I made a screenshot of a FAB with and without being nested in a ShimmerFrameLayout. 
Did you ever encounter that? Any ideas to fix this?
![shadow_overdraw](https://cloud.githubusercontent.com/assets/2833600/7064179/cf2020f6-deac-11e4-972b-120d440929c5.png)

**Comment by f-barth** [comment]
It seems as this behaviour is related to custom drawing of the FAB's shadow.

**Comment by ubuntudroid** [comment]
I know this has been posted quite some time ago, but I see the same behavior with `MaterialButton` - though only the first time it's added to the parent view group. 🤔 @f-barth did you manage to fix it in the end?
