### ISSUE TITLE
drawableLeft shimmer

### ISSUE THREAD

**Issue by ozanurkn** [facebook/shimmer-android#70]
How can i set only drawableLeft icon?

**Comment by xiphirx** [comment]
Not sure what you're asking, but you can always use ShimmerDrawable to set any sort of drawable.

**Comment by ozanurkn** [comment]
sorry for my bad english , i was asking i am using android:drawableLeft ="@drawable/ic_star_yellow_24dp" and i want to use shimmer library without text.. my code example below ;

<TextView
                                android:id="@+id/txt_check_opportunity"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_centerVertical="true"
                                android:layout_marginLeft="0dp"
                                android:layout_toRightOf="@+id/checkbox_opportunity"
                                android:drawableLeft="@drawable/ic_star_yellow_24dp"
                                android:text="@string/opportunity"
                                android:textSize="@dimen/text_medium_size"
                                android:textStyle="bold" />

**Comment by ozanurkn** [comment]
<TextView
                                android:id="@+id/txt_check_opportunity"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_centerVertical="true"
                                android:layout_marginLeft="0dp"
                                android:layout_toRightOf="@+id/checkbox_opportunity"
                                android:drawableLeft="@drawable/ic_star_yellow_24dp"
                                android:text="@string/opportunity"
                                android:textSize="@dimen/text_medium_size"
                                android:textStyle="bold" />

**Comment by xiphirx** [comment]
You cant set it directly from XML. You will need to use `setCompoundDrawables` in Java with a `ShimmerDrawable`

**Comment by ozanurkn** [comment]
Thanks you bro
