### ISSUE TITLE
Application doing so much work in main thread when shimmerFramelayout is added in layout file 

### ISSUE THREAD

**Issue by sakarayajitesh** [facebook/shimmer-android#73]
When I just add shimmerFramelayout to layout file and run, it is saying Skipped frames ,application doing so much work in main thread. When I remove shimmerFrameLayout and run, it works smoothly.

![shimmer](https://user-images.githubusercontent.com/22650227/50040074-9c43e100-0062-11e9-8c78-b9ba291eb514.png)
![shimmer output](https://user-images.githubusercontent.com/22650227/50040075-9cdc7780-0062-11e9-8a0d-bdc532d0dab1.png)
![without](https://user-images.githubusercontent.com/22650227/50040076-9cdc7780-0062-11e9-944a-4c06de12bb36.png)
![without output](https://user-images.githubusercontent.com/22650227/50040077-9cdc7780-0062-11e9-8b83-475362d54c7d.png)

**Comment by xiphirx** [comment]
This could be caused by a lot of different things, this isnt enough information to pinpoint it to shimmer.

**Comment by RGU5Android** [comment]
Hi @sakarayajitesh, after updating to version 0.5.0 the issue was no longer reproducible.
