### ISSUE TITLE
White shimmer above children 

### ISSUE THREAD

**Issue by mianaliasjad** [facebook/shimmer-android#78]
i have imageview insdie shimmer Frame i want to just white shimmer over it i have tried so many ways but can't achieve anything i just want white shimmer over my image view currently i am doing this but nothing happening i started it pragmatically 

                <com.facebook.shimmer.ShimmerFrameLayout
                    android:id="@+id/shimmer_view_img"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    ads:shimmer_highlight_color="@color/m_color_sky_blue"
                    ads:shimmer_base_alpha="1"
                    app:shimmer_auto_start="false">

                    <ImageView
                        android:id="@+id/iv_app_icon"
                        android:layout_width="70dp"
                        android:layout_height="70dp"
                        android:layout_gravity="center"
                        ads:srcCompat="@mipmap/white_lock" />

                </com.facebook.shimmer.ShimmerFrameLayout>

**Comment by xiphirx** [comment]
Try specifying `shimmer_colored="true"`

**Comment by mianaliasjad** [comment]
`shimmer_colored` makes my imageView white.

**Comment by mecoFarid** [comment]
Plus `shimmer_colored = true` applies to the first parent in the complex view hierarchy. All the children are gone now.

**Comment by xiphirx** [comment]
`Shimmer.ColorHighlightBuilder().setBaseAlpha(0.5f).setHighlightColor(0xffffffff.toInt())`

This works for me.

**Comment by omkar-tenkale** [comment]
> 
> 
> `Shimmer.ColorHighlightBuilder().setBaseAlpha(0.5f).setHighlightColor(0xffffffff.toInt())`
> 
> This works for me.

Doesnt work, makes the child white

**Comment by omkar-tenkale** [comment]
```
        Shimmer.ColorHighlightBuilder colorHighlightBuilder = new Shimmer.ColorHighlightBuilder();
        colorHighlightBuilder.setHighlightColor(getResources().getColor(R.color.colorWhite));
        colorHighlightBuilder.setHighlightAlpha(0.3f);
        colorHighlightBuilder.setRepeatCount(0);
        colorHighlightBuilder.setBaseAlpha(0);
        ui.shimmerContainer.setShimmer(colorHighlightBuilder.build())
```


     
```
        <FrameLayout
            android:id="@+id/actionRoot"
            android:background="@drawable/bg_round_button_green"
            android:layout_margin="8dp"
            android:layout_width="match_parent"
            android:layout_height="48dp" >

            <TextView
                android:textColor="@color/white"
                android:id="@+id/action"
                android:gravity="center"
                android:textSize="16dp"
                android:text="CHARGE  $ 232.23"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

            <com.facebook.shimmer.ShimmerFrameLayout
                android:id="@+id/shimmerContainer"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">
                <View
                    android:background="#000"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"/>
            </com.facebook.shimmer.ShimmerFrameLayout>

        </FrameLayout>
```
![ezgif com-gif-maker](https://user-images.githubusercontent.com/39808155/135272486-41990da6-a491-43fe-aaf9-b98ff98457b3.gif)

Nice na! :)

Mistake i was doing was 



        <com.facebook.shimmer.ShimmerFrameLayout
                android:id="@+id/shimmerContainer"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">
                <TextView
                    android:textColor="@color/white"
                    android:id="@+id/action"
                    android:gravity="center"
                    android:textSize="16dp"
                    android:text="CHARGE  $ 232.23"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />
            </com.facebook.shimmer.ShimmerFrameLayout>
```
