### ISSUE TITLE
remove mask after animation ends

### ISSUE THREAD

**Issue by xingxp** [facebook/shimmer-android#8]
maybe you should add autoStop property to shimmer
when repeat count reached, it will remove the mask.

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by xiphirx** [comment]
544c5687cc0f1b2e976cd43e806a5f82e81d6462
