### ISSUE TITLE
Please ShimmerFrameLayout needs to update version, cannot find class on android 3.3.2 build gradle

### ISSUE THREAD

**Issue by mochadwi** [facebook/shimmer-android#81]
Build gradle: classpath 'com.android.tools.build:gradle:3.3.2'

Shimmer version: 0.4.0

**EDITED:**
On build gradle version 3.3.2, the ShimmerFrameLayout v0.4.0 show error cannot find class.

**Comment by xiphirx** [comment]
I don't know what this means, you will need to provide more details here.

**Comment by mochadwi** [comment]
I've edited the description

**Comment by Quentinvk** [comment]
I got the same, unresolved class in xml after adding the dependency.

**Comment by Quentinvk** [comment]
com.facebook.shimmer.ShimmerFrameLayout is unresolved in 0.5.0

**Comment by gonzalonm** [comment]
I have compile errors for some resources of my drawable folders. They already exist but after add the library, I got errors like this one:

`AAPT: error: resource drawable/button (aka mypackage:drawable/button) not found.`

I'm not sure if this error related with this thread.

BTW, this is the configuration I have:

`implementation "com.facebook.shimmer:shimmer:0.5.0"`

**Comment by xiphirx** [comment]
The sample project in this repo works just fine which confirms that there shouldn't be anything wrong with the artifact. I'm not sure what the issues would be per specific project configuration, so I'm closing this task.
