### ISSUE TITLE
Duration Not Found

### ISSUE THREAD

**Issue by amalive** [facebook/shimmer-android#87]
After update shimmer gradle  to 0.4, the duration is not found

 implementation 'com.facebook.shimmer:shimmer:0.4.0'

/Users/XX/Documents/Workspace/Shimmer/app/src/main/res/layout/activity_main.xml:10: 
AAPT: error: attribute duration (aka xxx.xxxx.shimmer:duration) not found.

**Comment by xiphirx** [comment]
Its called `shimmer_duration` now.
