### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by somghosh** [facebook/shimmer-android#9]
I am seeing the following with LeakCanary - I think it is because I am exiting the activity while there is some animation thread running. What is the possible solution for this?

05-20 17:10:33.377  13526-14611/com.gmspartnersltd.earthmiles.debug D/LeakCanary﹕ In com.gmspartnersltd.earthmiles.debug:1.6:6.
    \* com.gmspartnersltd.earthmiles.views.mainthreetabs.rewardsfragment.RewardsSubFragment has leaked:
    \* GC ROOT android.view.Choreographer$FrameDisplayEventReceiver.this$0
    \* references android.view.Choreographer.mCallbackQueues
    \* references array android.view.Choreographer$CallbackQueue[].[1]
    \* references android.view.Choreographer$CallbackQueue.mHead
    \* references android.view.Choreographer$CallbackRecord.action
    \* references android.animation.ValueAnimator$AnimationHandler.mAnimations
    \* references java.util.ArrayList.array
    \* references array java.lang.Object[].[0]
    \* references android.animation.ValueAnimator.mUpdateListeners
    \* references java.util.ArrayList.array
    \* references array java.lang.Object[].[0]
    \* references com.facebook.shimmer.ShimmerFrameLayout$2.this$0 (anonymous class implements android.animation.ValueAnimator$AnimatorUpdateListener)
    \* references com.facebook.shimmer.ShimmerFrameLayout.mContext
    \* references android.view.ContextThemeWrapper.mBase
    \* references com.gmspartnersltd.earthmiles.views.MainActivity.mFragments
    \* references android.app.FragmentManagerImpl.mAdded
    \* references java.util.ArrayList.array
    \* references array java.lang.Object[].[0]
    \* references com.gmspartnersltd.earthmiles.views.mainthreetabs.rewardsfragment.RewardsFragment.mTabsLinearLayout
    \* references android.widget.LinearLayout.mParent
    \* references com.astuetz.PagerSlidingTabStrip.pager
    \* references android.support.v4.view.ViewPager.mAdapter
    \* references com.gmspartnersltd.earthmiles.views.mainthreetabs.rewardsfragment.RewardsSubTabAdapter.mCurrentPrimaryItem
    \* leaks com.gmspartnersltd.earthmiles.views.mainthreetabs.rewardsfragment.RewardsSubFragment instance
    \* Reference Key: 314744a1-c40a-4b0d-aec1-547d7117ace4
    \* Device: Genymotion generic Google Nexus 5 - 5.0.0 - API 21 - 1080x1920 vbox86p
    \* Android Version: 5.0 API: 21
    \* Durations: watch=5010ms, gc=123ms, heap dump=829ms, analysis=4626ms

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by EKami** [comment]
Any update on this? I'm still having the issue with version `0.1.0`

**Comment by lawloretienne** [comment]
There is still no response on this.  I guess this library has been abandoned.

**Comment by hussi1** [comment]
Should i deem this project unstable ?

**Comment by xiphirx** [comment]
544c5687cc0f1b2e976cd43e806a5f82e81d6462
