### ISSUE TITLE
showShimmer(true) would not start the shimmer

### ISSUE THREAD

**Issue by fullmoon6661** [facebook/shimmer-android#91]
Calling `showShimmer(true)` while having attribute `app:shimmer_auto_start="false"` would show  the shimmer but doesn't start the shimmer. I'm guessing because the following function would return immediately without checking if the shimmer has started.
```java
/**
* Sets the ShimmerDrawable to be visible.
* @param startShimmer Whether to start the shimmer again.
*/
public void showShimmer(boolean startShimmer) {
    if (mShowShimmer) { // mShowShimmer=true
        return;
    }
    mShowShimmer = true;
    if (startShimmer) {
        startShimmer();
    }
}
```

**Comment by xiphirx** [comment]
The param there is just a convenience when showing the shimmer the first time. If its already visible then you want to use `startShimmer()`. The ergonomics of the function suck though, so I'll remove the early return since it doesn't seem to be preventing much
