### ISSUE TITLE
View.getVisibility() NullPointerException

### ISSUE THREAD

**Issue by siscofran999** [facebook/shimmer-android#94]
Hello, i have a problem on getVisibility when using shimmer layout that made velocity alert from firebase crashlytics. Is there any solution for this problem? Currently i used version 0.5.0
thx
<img width="849" alt="Screen Shot 2020-04-23 at 11 19 19" src="https://user-images.githubusercontent.com/23308524/80058742-52bbae00-8554-11ea-85f7-eea3c16374a6.png">
![photo_2020-04-23_11-20-03](https://user-images.githubusercontent.com/23308524/80058768-69fa9b80-8554-11ea-8c44-e7638746c9cb.jpg)

**Comment by xiphirx** [comment]
That line is `super.onLayout(...)` which means its within `FrameLayout`. It looks like you somehow have a null child view in the layout.
